# Generated by Django 5.0.3 on 2024-04-21 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_choice_is_correct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='is_correct',
            field=models.FloatField(choices=[(0, '0'), (0.5, '0.5'), (1, '1')]),
        ),
    ]
